<RootController>:
    screen_manager: screen_manager
    toolbar:toolbar
    nav_drawer: nav_drawer    
    orientation: "vertical"

    MDTopAppBar:
        id: toolbar
        title: "Digital Oracle"
        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
        elevation: 4

    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager

        MDNavigationDrawer:
            id: nav_drawer

            MDNavigationDrawerMenu:

                MDNavigationDrawerLabel:
                    text: "Navigation"

                MDNavigationDrawerItem:
                    text: "Home"
                    icon: "home"
                    on_release: root.goto("home")
                    text_color: 0.2,0.1,0.6,1

                MDNavigationDrawerItem:
                    text: "Tarot Reading"
                    icon: "cards"
                    on_release: root.goto("tarot")
                    text_color: 0.1,0.3,0.6,1
                
                MDNavigationDrawerItem:
                    text: "Reading History"
                    icon: "history"
                    on_release: root.goto("history")
                    text_color: 0.3,0.2,0.6,1
                    
                MDNavigationDrawerItem:
                    text: "Explore"
                    icon: "card"
                    on_release: root.goto("deck")
                    text_color: 0.4,0.1,0.6,1

                MDNavigationDrawerItem:
                    text: "Settings"
                    icon: "cog"
                    on_release: root.goto("settings")
                    text_color: 0.5,0.1,0.6,1
                
                MDNavigationDrawerItem:
                    text: "Exit"
                    icon: "exit"
                    on_release: root.app.stop()
                    text_color: 0.8,0,0.2,1


<HomeScreen>:
    logo:logo
    app_title:app_title
    
    name: "home"
    
    MDBoxLayout:
        orientation: "vertical"

        MDBoxLayout:
            orientation: "vertical"
            size_hint_y: 0.4
            padding: "10dp"
            spacing: "10dp"

            SpinningLogo:
                id: logo
                source: "data/logo.png"
                size_hint_y: 0.7
                pos_hint: {"center_x": 0.5}

            MDLabel:
                id: app_title
                text: f"The\nDigital Oracle"
                font_style: "H3"
                halign: "center"
                valign: "middle"
                size_hint_y: 0.3
                text_size: self.size
                theme_text_color: "Custom"
                text_color: 0.5, 0, 1, 1

        MDBoxLayout:
            orientation: "vertical"
            size_hint_y: 0.6

            MDLabel:
                text:root.get_cotd()
                halign: "center"
                theme_text_color: "Custom"
                text_color: 0.5,0.1,0.5,1


<SettingsScreen>:
    name: "settings"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
        pos_hint:{"center_x":0.5}

        Widget:
            size_hint_y: None
            height: dp(20)

        MDBoxLayout:
            orientation: "vertical"
            padding: dp(10)
            size_hint_y: 0.3
            pos_hint:{"center_x":0.5}

            MDLabel:
                text: "Google AI API Key"
                font_style: "H6"
                size_hint_y: None
                height: self.texture_size[1]

            MDTextField:
                id: api_key_input
                hint_text: "Enter your Google AI API Key"

            MDBoxLayout:
                orientation: "horizontal"
                padding: dp(10)
                spacing: dp(10)
                size_hint_y: None
                size_hint_x:1
                height: dp(50)
                pos_hint: {"center_x": 0.5}

                MDRaisedButton:
                    text: "Reset API Key"
                    on_release: root.reset_api_key()

                MDRaisedButton:
                    text: "Save API Key"
                    on_release: root.save_api_key(api_key_input.text)

            Widget:

            MDBoxLayout:
                orientation: "vertical"
                size_hint_y:0.7
                padding: 10
                spacing: 10
                
                MDLabel:
                    text:"version 1.1"
                    halign:"center"
                    valign:"bottom"
                    font_size:"10sp"


<TarotScreen>:
    in_field: in_field

    name: "tarot"

    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(10)
        padding: dp(10)
        pos_hint:{"center_x":0.5}

        MDLabel:
            text: "What do you seek?"
            font_syle: "H4"
            halign: "center"
            valign:"top"
            size_hint_y: None
            height: self.texture_size[1]

        MDTextField:
            id: in_field
            hint_text: "Ask the stars anything..."
            size_hint: 0.7,0.7
            #height: dp(150)
            pos_hint: {"center_x":0.5}
            multiline: True
        
        MDBoxLayout:
            orientation:"horizontal"
            pos_hint:{"center_x":0.5}
            padding: 15
            spacing: 15

            MDRaisedButton:
                text: "Ask (Full)"
                size_hint: 0.3, None
                height: dp(30)
                on_release: root.ask_pressed()
            
            MDRaisedButton:
                text: "Yes, No, Maybe?"
                size_hint: 0.3, None
                height: dp(30)
                on_release: root.ask_yn()
            
        Widget:


<ReadingScreen>:
    res_label:res_label
    current_status: current_status

    name: "reading"

    MDBoxLayout:
        orientation: "vertical"
        
        MDLabel:
            id: current_status
            size_hint_x: 1.0
            pos_hint:{"center_x":0.5}
            halign:"center"
            size_hint_y: None
            height: dp(100)
            theme_text_color: "Custom"
            text_color: 0.85, 0.75, 0.45, 1
        
        MDScrollView:
            size_hint_y: 0.8
            do_scroll_x: False
            do_scroll_y: True
            
            MDLabel:
                id: res_label
                size_hint: 0.8, None
                height: self.texture_size[1]
                text_size: self.width, None
                halign: "left"
                valign: "top"
        
        MDRaisedButton:
            text:"Ok"
            size_hint: 0.3, None
            height: dp(30)
            on_release: root.ok_pressed()


<HistoryScreen>:
    name: "history"
    
    MDBoxLayout:
        orientation: "vertical"
        
        MDScrollView:
            MDList:
                id: history_list


<PastReading>:
    past_inquiry:past_inquiry
    past_response:past_response
    
    name: "past"
    
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(10)
        spacing: dp(10)
        
        MDLabel:
            id: past_inquiry
            size_hint: 0.8,0.3
            halign: "center"
            text_color: 0.5, 0.5, 0.1, 1
            pos_hint:{"center_x":0.5}
        
        MDScrollView:
            size_hint: 0.9, 0.9
            do_scroll_x: False
            do_scroll_y: True
            pos_hint:{"center_x":0.5}
            
            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                
                MDLabel:
                    id: past_response
                    text_color: 0.5, 0.2, 0.3, 1
                    size_hint_y: None
                    height: self.texture_size[1]
                    text_size: self.width, None
                    halign: "left"
                    valign: "top"
        
        MDBoxLayout:
            orientation: "horizontal"
            size_hint: 1, 0.2
            padding: dp(10)
            spacing: dp(10)
        
        MDRaisedButton:
            text: "Back"
            size_hint: 0.3, None
            height: dp(50)
            on_release: root.manager.current = "history"

        MDRaisedButton:
            text: "Delete"
            size_hint: 0.3, None
            height: dp(50)
            on_release: root.delete_reading()


<DeckScreen>:
    name: "deck"
    
    MDBoxLayout:
        orientation: "vertical"
        
        MDCarousel:
            id: tarot_carousel
            scroll_timeout: 200
            scroll_distance: dp(70)
            direction: "right"
            loop: True


<YesOrNoScreen>:
    name: "yn"

    MDBoxLayout:
        orientation:"vertical"
        padding: 10
        spacing: 10






#
#
#
#
<FlippableCard>:
    FloatLayout:
        id: container
        size: root.size
        pos: root.pos

        canvas.before:
            PushMatrix
            Scale:
                x: root.scale_x
                y: 1
                z: 1
                origin: self.center
        canvas.after:
            PopMatrix

        MDCard:
            id: card
            orientation: "vertical"
            padding: "16dp"
            spacing: "10dp"
            radius: [20]
            elevation: 6
            size_hint: 0.9, 0.9
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            on_press: root.flip()


<SpinningLogo>:
    canvas.before:
        PushMatrix
        Rotate:
            angle: self.angle
            origin: self.center
    canvas.after:
        PopMatrix