<RootController>:
    screen_manager: screen_manager
    toolbar:toolbar
    nav_drawer: nav_drawer
    
    orientation: "vertical"

    MDTopAppBar:
        #canvas.before:
#            Color:
#                rgba: [0.2,0.4,0.4,1]
#            RoundedRectangle:
#                pos: self.pos
#                size: self.size
#                # The radius of the corners [top-left, top-right, bottom-right, bottom-left]
#                radius: [25, 25, 25, 25] 
            
        id: toolbar
        title: "Digital Oracle"
        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
        elevation: 4

    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager

            HomeScreen:
                name: "home"

            TarotScreen:
                name: "tarot"

            SettingsScreen:

        MDNavigationDrawer:
            id: nav_drawer

            MDNavigationDrawerMenu:

                MDNavigationDrawerLabel:
                    text: "Navigation"

                MDNavigationDrawerItem:
                    text: "Home"
                    icon: "home"
                    on_release: root.goto("home")

                MDNavigationDrawerItem:
                    text: "Tarot Reading"
                    icon: "cards"
                    on_release: root.goto("tarot")

                MDNavigationDrawerItem:
                    text: "Settings"
                    icon: "cog"
                    on_release: root.goto("settings")


<HomeScreen>:
    name: "home"
    
    #canvas.before:
#        Color:
#            rgba: root.get_primary()
#        RoundedRectangle:
#            pos: self.pos
#            size: self.size
#            # The radius of the corners [top-left, top-right, bottom-right, bottom-left]
#            radius: [25, 25, 25, 25] 
    
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(15)
        spacing: dp(15)
        
    


<SettingsScreen>:
    name: "settings"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
        size_hint_y: 0.3

        MDLabel:
            text: "Google AI API Key"
            font_style: "H6"
            size_hint_y: None
            height: self.texture_size[1]

        MDTextField:
            id: api_key_input
            hint_text: "Enter your Google AI API Key"
            text: root.api_key or ""

        MDBoxLayout:
            orientation: "horizontal"
            padding: dp(10)
            spacing: dp(10)
            size_hint_y: None
            height: dp(50)
            pos_hint: {"center_x": 0.5}

            MDRaisedButton:
                text: "Reset API Key"
                on_release: root.reset_api_key()

            MDRaisedButton:
                text: "Save API Key"
                on_release: root.save_api_key(api_key_input.text)
